# --- config.yaml ---
# File cấu hình cho ứng dụng Modbus Go Gateway

logging:
  level: "info"  # debug, info, warn, error
  enable_csv: true # Bật/tắt ghi file CSV dữ liệu song song
  # Mẫu tên file log cho trạng thái và lỗi
  status_error_log_file: "gateway_status_%s.log" # %s = timestamp
  # Mẫu tên file log cho dữ liệu đọc được (JSON)
  data_log_file: "modbus_data_logrus_%s.log" # %s = timestamp (Tên file có thể đổi sau)

storage:
  {} # Hiện không có cấu hình storage đặc biệt

devices:
  - name: "Schneider_PM_COM3_ID1"
    enabled: true
    tags: { location: "Tu_Dien_Chinh", panel: "Panel_1", slave_id_tag: "1" }
    register_list_file: "registers_pm2120.csv"
    connection: { type: "rtu", port: "COM3", baudrate: 19200, databits: 8, parity: "N", stopbits: 1, slaveid: 1, timeout_ms: 1000, address_base: 1 }
    polling_interval_ms: 1500

  - name: "Schneider_PM_COM3_ID2"
    enabled: true
    tags: { location: "Tu_Dien_Chinh", panel: "Panel_2", slave_id_tag: "2" }
    register_list_file: "registers_pm2120.csv"
    connection: { type: "rtu", port: "COM3", baudrate: 19200, databits: 8, parity: "N", stopbits: 1, slaveid: 2, timeout_ms: 1000, address_base: 1 }
    polling_interval_ms: 1700
      
  - name: "MFM383A_COM3"
    enabled: false
    tags: { location: "LAB_MR.TAM", panel: "Panel_1", slave_id_tag: "3" }
    register_list_file: "registers_mfm383a.csv"
    connection: { type: "rtu", port: "COM3", baudrate: 9600, databits: 8, parity: "N", stopbits: 1, slaveid: 5, timeout_ms: 1000, address_base: 0 }
    polling_interval_ms: 1500
